### ISSUE TITLE
Issues while trying to train

### ISSUE THREAD

**Issue by ofirkris** [goldhuang/SRGAN-PyTorch#3]
input:

> python3 train.py --train_set=data/train <

Error:
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 49, in main
    train_loader = DataLoader(dataset=train_set, num_workers=2, batch_size=batch_size, shuffle=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

What am I doing wrong?

**Comment by ofirkris** [comment]
Am I supposed to export all images from "danbooru" folders into one singal folder for training?
